# Generated by Django 3.2.13 on 2024-04-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectlocal', '0002_accoutinfo_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermiss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wantGo',
        ),
    ]
