# Generated by Django 3.2.13 on 2024-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectlocal', '0004_wantgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='xxRuter',
            fields=[
                ('cityId', models.BigAutoField(primary_key=True, serialize=False)),
                ('daysun', models.IntegerField()),
                ('daynumber', models.IntegerField()),
                ('title', models.CharField(max_length=160)),
                ('titledetail', models.CharField(max_length=460)),
                ('suitpeople', models.CharField(max_length=60)),
                ('suitmonth', models.CharField(max_length=60)),
                ('roter', models.CharField(max_length=160)),
                ('roterdetail', models.CharField(blank=True, max_length=1000, null=True)),
                ('daynHref', models.CharField(max_length=300)),
                ('roterImg', models.CharField(blank=True, max_length=1000, null=True)),
                ('fooddetail', models.CharField(blank=True, max_length=1000, null=True)),
                ('foodImg', models.CharField(blank=True, max_length=200, null=True)),
                ('staydetail', models.CharField(blank=True, max_length=1000, null=True)),
                ('stayImg', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'xxruter',
                'managed': False,
            },
        ),
    ]
