# Generated by Django 3.2.13 on 2024-04-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectlocal', '0005_xxruter'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imgUrl', models.CharField(blank=True, max_length=160, null=True)),
                ('cityName', models.CharField(blank=True, max_length=460, null=True)),
                ('selectId', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityTepyFour',
            fields=[
                ('cityId', models.BigAutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(blank=True, max_length=100, null=True)),
                ('HotelPoints', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'want_go',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('cityId', models.BigAutoField(primary_key=True, serialize=False)),
                ('cityTip', models.CharField(blank=True, max_length=160, null=True)),
                ('cityName', models.CharField(max_length=460)),
                ('HotelName', models.CharField(max_length=60)),
                ('Hotelslocal', models.CharField(blank=True, max_length=160, null=True)),
                ('Hotelsscore', models.CharField(blank=True, max_length=100, null=True)),
                ('Hotelsmoney', models.CharField(blank=True, max_length=300, null=True)),
                ('Hotelsytype', models.CharField(blank=True, max_length=300, null=True)),
                ('Hotelfherf', models.CharField(blank=True, max_length=50, null=True)),
                ('Hotelfimg', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Hotal',
                'managed': False,
            },
        ),
    ]
